---
title: "Bnlearn"
author: "Nick Zelada"
date: "9/15/2021"
output: pdf_document
---

```{r}
#,
#                    "Close", "NegPercent",
#                    "Close", "PosPercent",
#                    "Close", "Polarity",
#                    "Close", "NeuPercent",
#           8         "High", "NegPercent",
#                    "High", "PosPercent",
#                   "High", "Polarity",
#                    "High", "NeuPercent",
#                    "Low", "NegPercent",
#                    "Low", "PosPercent",
#                    "Low", "Polarity",
#                    "Low", "NeuPercent"

# Here I call the Dataset that I have created from the analysis.
library(bnlearn)
#This is everything
dataset1=read.csv('/Users/nickzelada/Desktop/Capstone/anaPlusSPXJune2.csv')
```
```{r}
# I factor to create levels from the daily percentage of Neg, Neu, and Polarity
# I also factor the daily mean of Polarity.
# I factor the close 
dataset1$NegPercent = factor(dataset1$NegPercent)
dataset1$NeuPercent = factor(dataset1$NeuPercent)
dataset1$PosPercent = factor(dataset1$PosPercent)
dataset1$Close = factor(dataset1$Close)
#dataset1$High = factor(dataset1$High)
#dataset1$Low = factor(dataset1$Low)
dataset1$Polarity = factor(dataset1$Polarity)
#grainger takes two time series, sees
```
```{r}
# Now I created the nodes.
dag <- empty.graph(nodes = c("Polarity","NegPercent","NeuPercent","Close","PosPercent"))
```
```{r}
# Here I create directions for the nodes, here I put them from Close to the 
# percent and polarity, as a way to see the conversation is talked about after
# the price changes. 
arc.set <- matrix(c("Close", "NegPercent",
                  "Close","PosPercent",
                    "Close", "Polarity",
                    "Close", "NeuPercent"),
                  byrow = TRUE, ncol = 2,
                  dimnames = list(NULL, c("from", "to")))
```
```{r}
dataset1 = dataset1[-1:-4]
```
```{r}
dataset1 = dataset1[-2]
```
```{r}
dataset1 = dataset1[-5:-7]
```
```{r}
dataset1 = dataset1[-5:-7]
```
```{r}
dataset1 = dataset1[-6:-8]
```
```{r}
dataset1 = dataset1[-6]
```


```{r}
# The arches 
arcs(dag) <- arc.set
```

```{r}
# The nodes
nodes(dag)
```
```{r}
# We have 4 arcs since we have 4 from and to
# Close is the parent, the others are the Child
# Direct dependencies, because they are go directing from Close to the others
arcs(dag)
```
```{r}
## Drop one of them !!!
# Get Standard deviation of polarity, of the sentiment
# blacklist!
plot(dag)
```

##
#
```{r}
graphviz.plot(dag, layout = "dot")
```
```{r}
# Using hill-climbing
#dag = hc(dataset1, whitelist = arc.set)
```
```{r}
# Here we see the model, which has the parent, and each of the arcs relationships
# We create the network here.
# 5 nodes, 4 arcs
# average branching factor is by 4/5 = 0.8
# average neighbourhood size:1.60, because in total there is 8 visitors in all of
# the neighborhoods, but 5 nodes, so 8/5

#The Markov blanket of a node contains the node's parents, children and children's parents
# We get 1.60 for Markov blanket, because we have 4 children and 1 parent. The
# parent contains 4 kids, and each of the child node contains 1 parent. So in 
# total there is 5 nodes, while the parent holding 4 kids, and each of the childrens
# having a relationship with the parent. So we get 8, then divide it by 5 nodes.
# we get 1.60
dag
```

```{r}
# Next, we fit it into a structure to replace the network conditional
#maximum likelihood estimator
# Find the maximum likelihood of something happening based on the frequency of it.
# 
bn.mle <- bn.fit(dag, dataset1,, method = "mle")
```
```{r}
bn.mle
```
```{r}
#Bayes find the probabilities based on the prior information given. Such as that
# it takes to account everything into account. mle is different in the sense, that
# it goes by frequency for each relationship, not the whole prior data.
bn.bayes <- bn.fit(dag, dataset1,, method = "bayes")
```
```{r}

bn.bayes
```
```{r}
#mutual information test
#Conditional independence tests focus on the presence of individual arcs
# checks if the arcs are probabilistically independent from parent

#Null Hypothesis: NegPercent is probabilistically independent from Close
#Alternative: NegPercent isn't probabilistically independent from Close
ci.test("Close", c("NegPercent"), test = "mi", data = dataset1)
#dependence relation- ship encoded by Close and PosPercent is not significant 
#given the current DAG structure
```
```{r}
#Here is a chart of each arc and their "p-value"
arc.strength(dag, data = dataset1, criterion = "mi")
```
```{r}
#Unlike conditional independence tests, network scores focus on the DAG as a whole
#Bayesian Information criterion
score(dag, data = dataset1, type = "bic")
```

```{r}
library(gRain)
```
```{r}
junction <- compile(as.grain(bn.mle))
```
```{r}
junction
```
```{r}
jsex <- setEvidence(junction, nodes = "Close", states = "INCREASE")
```
```{r}
querygrain(jsex, nodes = "NegPercent")$NegPercent
```
```{r}
bn.fit.barchart(bn.bayes$Polarity,main = "Probabilities for Daily Polarity mean on Close",
                xlab = "Pr(Polarity|Close)", ylab = "Polarity daily means")

```
```{r}
bn.fit.barchart(bn.bayes$NeuPercent,main = "Probabilities for Neutral on Close",
                xlab = "Pr(Neutral|Close)", ylab = "Daily neutral percentage")

```
```{r}
bn.fit.barchart(bn.bayes$NegPercent,main = "Probabilities for Negative Percentage on Close",
                xlab = "Pr(Negative|Close)", ylab = "Daily negative percentage")

```
```{r}
bn.fit.barchart(bn.bayes$PosPercent,main = "Probabilities for Positive Percentage on Close",
                xlab = "Pr(Positive|Close)", ylab = "Daily Positive percentage")

```
```{r}
#Now lets do last hour of the day before.
dataset2=read.csv('/Users/nickzelada/Desktop/Capstone/anaPlusSPX8.csv')
```

```{r}
# I factor to create levels from the daily percentage of Neg, Neu, and Polarity
# I also factor the daily mean of Polarity.
# I factor the close 
dataset2$NegPercent = factor(dataset2$NegPercent)
dataset2$NeuPercent = factor(dataset2$NeuPercent)
dataset2$PosPercent = factor(dataset2$PosPercent)
dataset2$Close = factor(dataset2$Close)
dataset2$Polarity = factor(dataset2$Polarity)
#grainger takes two time series, sees
```
```{r}
# Now I created the nodes.
dag3 <- empty.graph(nodes = c("Polarity","NegPercent","NeuPercent","PosPercent","Close"))
```
```{r}
# Here I create directions for the nodes, here I put them from Close to the 
# percent and polarity, as a way to see the conversation is talked about after
# the price changes. 
arc.set3 <- matrix(c("Close", "NegPercent",
                    "Close","PosPercent",
                    "Close", "Polarity",
                    "Close", "NeuPercent"),
                  byrow = TRUE, ncol = 2,
                  dimnames = list(NULL, c("from", "to")))
```
```{r}
dataset2 = dataset2[-1:-4]
```
```{r}
dataset2 = dataset2[-2]
```

```{r}
dataset2 = dataset2[-5:-7]
```

```{r}
dataset2 = dataset2[-6:-9]
```
```{r}
# The arches 
arcs(dag3) <- arc.set3
```

```{r}
# The nodes
nodes(dag3)
```
```{r}
# We have 4 arcs since we have 4 from and to
# Close is the parent, the others are the Child
# Direct dependencies, because they are go directing from Close to the others
arcs(dag3)
```
```{r}
## Drop one of them !!!
# Get Standard deviation of polarity, of the sentiment
# blacklist!
plot(dag3)
```
```{r}
graphviz.plot(dag3, layout = "dot")
```
```{r}
dag3
```
```{r}
# Next, we fit it into a structure to replace the network conditional
#maximum likelihood estimator
# Find the maximum likelihood of something happening based on the frequency of it.
# 
bn.mle3 <- bn.fit(dag3, dataset2, method = "mle")
```
```{r}
bn.mle3
```
```{r}
#Bayes find the probabilities based on the prior information given. Such as that
# it takes to account everything into account. mle is different in the sense, that
# it goes by frequency for each relationship, not the whole prior data.
bn.bayes3 <- bn.fit(dag3, dataset2, method = "bayes")
```
```{r}

bn.bayes3
```
```{r}
#mutual information test
#Conditional independence tests focus on the presence of individual arcs
# checks if the arcs are probabilistically independent from parent

#Null Hypothesis: NegPercent is probabilistically independent from Close
#Alternative: NegPercent isn't probabilistically independent from Close
ci.test("Close", c("NegPercent"), test = "mi", data = dataset2)
#dependence relation- ship encoded by Close and PosPercent is not significant 
#given the current DAG structure
```
```{r}
#Here is a chart of each arc and their "p-value"
arc.strength(dag3, data = dataset2, criterion = "mi")
```
```{r}
#Unlike conditional independence tests, network scores focus on the DAG as a whole
#Bayesian Information criterion
score(dag3, data = dataset2, type = "bic")
```
```{r}
library(gRain)
```
```{r}
junction3 <- compile(as.grain(bn.mle3))
```
```{r}
junction3
```
```{r}
jsex3 <- setEvidence(junction3, nodes = "Close", states = "INCREASE")
```
```{r}
querygrain(jsex3, nodes = "NegPercent")$NegPercent
```
```{r}
bn.fit.barchart(bn.bayes3$Polarity,main = "Probabilities for Polarity on Close",
                xlab = "Pr(Polarity|Close)", ylab = "Polarity daily means")

```

```{r}
bn.fit.barchart(bn.bayes3$NeuPercent,main = "Probabilities for Neutral on Close",
                xlab = "Pr(Neutral|Close)", ylab = "Daily neutral percentage")

```
```{r}
bn.fit.barchart(bn.bayes3$NegPercent,main = "Probabilities for Negative on Close",
                xlab = "Pr(Negative|Close)", ylab = "Daily negative percentage")

```
```{r}
bn.fit.barchart(bn.bayes3$PosPercent,main = "Probabilities for Positive on Close",
                xlab = "Pr(Negative|Close)", ylab = "Daily negative percentage")
```












