---
title: "Capstone"
author: "Nick Zelada"
date: "7/15/2021"
output: pdf_document
---

```{r}
## call the csv files
df1=read.csv('/Users/nickzelada/Desktop/Capstone/df1.csv')
spx=read.csv('/Users/nickzelada/Desktop/Capstone/spx.csv')
dji=read.csv('/Users/nickzelada/Desktop/Capstone/dji.csv')
```

```{r}
#convert the polarity
df1$Polarity[df1$Analysis == 'Positive'] <- 1
df1$Polarity[df1$Analysis == 'Neutral'] <- 0
df1$Polarity[df1$Analysis == 'Negative'] <- -1
```

```{r}
#find the daily mean
require(data.table)
result <- aggregate(Polarity~created_at, data= df1, FUN='mean')
```

```{r}
#filter to have only the month of june for the daily mean
library(dplyr) 
filtered = result %>% 
  filter(created_at >= as.Date("2020-06-01") & created_at <= as.Date("2020-06-30"))

```
```{r fig.width = 10}
library(ggplot2)
library(ggthemes)
library(plotly)

graph=ggplot(data=filtered , aes(x = created_at, y = Polarity))+
  geom_path(aes(group=1))+geom_point()
  
graph
```

```{r}
df2=read.csv('/Users/nickzelada/Desktop/Capstone/df1.csv')

```

```{r}
plothist <- ggplot(df2, aes(x = df2$Polarity, fill = "score", 
    )) + xlab("Date") + ylab("Number of Tweets") + ggtitle("Sentiment Score") + geom_histogram()

```
```{r}
#Group it by day and analysis
groupAnalysis = df2%>% group_by(created_at, Analysis)%>%count()
groupAnalysis
```
```{r}
groupAnalysisSpx = aggregate(df2$SPXCount, by=list(Category=df2$created_at), FUN=sum)
groupAnalysisSpx
```
```{r}
groupAnalysisCovid = aggregate(df2$CovidCount, by=list(Category=df2$created_at), FUN=sum)
groupAnalysisCovid
```
```{r}
filtered2 = groupAnalysis %>% 
  filter(created_at >= as.Date("2020-06-01") & created_at <= as.Date("2020-06-30"))
```


```{r fig.width = 10}
#daily number of tweets by group
qw<-ggplot(filtered2, aes(x=created_at,y=n, group=Analysis, color=Analysis ))+geom_line()

qw
```
```{r}

```

```{r}
df2$positive <- as.numeric(df2$Polarity > 
    0)

df2$negative <- as.numeric(df2$Polarity < 
    0)

df2$neutral <- as.numeric(df2$Polarity == 
    0)


```
```{r}


anaNeu = subset(groupAnalysis, Analysis == "Neutral")
anaNeg = subset(groupAnalysis, Analysis == "Negative")
anaPos = subset(groupAnalysis, Analysis == "Positive")


```
```{r}
colnames(anaNeu)[3] <- "Neutral"
colnames(anaNeg)[3] <- "Negative"
colnames(anaPos)[3] <- "Positive"
```
```{r}
anaNeu = anaNeu[-2]
anaNeg = anaNeg[-2]
anaPos = anaPos[-2]
```
```{r}
ana = merge(anaNeg, anaNeu)
ana = merge(ana,anaPos)
ana = merge(ana,filtered)
```
```{r}
ana$sum=ana$Negative+ana$Neutral+ana$Positive
```
```{r}
ana$NegPercent = round((ana$Negative/ana$sum)*100)
ana$NeuPercent = round((ana$Neutral/ana$sum)*100)
ana$PosPercent = round((ana$Positive/ana$sum)*100)
```
```{r}
spx = spx[-6]
spx = spx[-6]
spx = spx[-6]
```
```{r}
colnames(ana)[1] <- "Date"

```
```{r}
colnames(groupAnalysisCovid)[1] <- "Date"
colnames(groupAnalysisCovid)[2] <- "CovidKeywords"
colnames(groupAnalysisSpx)[1] <- "Date"
colnames(groupAnalysisSpx)[2] <- "SPXKeywords"
```
```{r}
keyWordsMerge = inner_join(groupAnalysisSpx,groupAnalysisCovid, by= "Date" )
```

```{r}
anaPlusSPX = inner_join(ana,spx, by= "Date" )
```

```{r}
anaPlusSPX = inner_join(anaPlusSPX,keyWordsMerge, by= "Date" )
```
```{r}
anaPlusSPX$PerSPX = round((anaPlusSPX$SPXKeywords/anaPlusSPX$sum)*100)
anaPlusSPX$PerCovid = round((anaPlusSPX$CovidKeywords/anaPlusSPX$sum)*100)
```
```{r}
anaPlusSPXJune= anaPlusSPX[anaPlusSPX$Date >= "2020-06-01" & anaPlusSPX$Date <= "2020-06-31",]


```
```{r}
colnames(filtered2)[1] <- "Date"
#filtered2$sum = inner_join(filtered2,sum, by= "created_at" )
```
```{r}
sum=anaPlusSPX
#filtered2$sum = inner_join(filtered2,anaPlusSPX$sum, copy= TRUE,by= "Date" )
```
```{r}
sum=sum[-2:-5]
```
```{r}
sum=sum[-3:-13]
```
```{r}
filtered2 = inner_join(filtered2,sum,by= "Date" )
```
```{r}
filtered2$percent=round((filtered2$n/filtered2$sum)*100)
```
```{r fig.width = 10}
qw1<-ggplot(filtered2, aes(x=Date,y=percent, group=Analysis, color=Analysis ))+geom_line()
#daily percentage of tweets by group
qw1
```
```{r fig.width = 10}
ggplot(anaPlusSPXJune) +
  
  geom_line( aes(x=Date,y=Close, group = 1, color = "Closing Price SPX")) + 
  geom_line( aes(x=Date,y=NegPercent*150, group = 1, color = "Negative Percentage"))+ # Divide by 10 to get the same range than the temperature
  
  scale_y_continuous(
    
    # Features of the first axis
    name = "Close",
    
    # Add a second axis and specify its features
    sec.axis = sec_axis(~./150, name="Negative Percent")
  )
#ggplot(anaPlusSPXJune, aes(Date,factor(Close),group=1))+geom_line()
```
```{r fig.width = 10}
ggplot(anaPlusSPXJune) +
  
  geom_line( aes(x=Date,y=Close, group = 1, color = "Closing Price SPX")) + 
  geom_line( aes(x=Date,y=PosPercent*55, group = 1, color = "Positive Percentage"))+ # Divide by 10 to get the same range than the temperature
  
  scale_y_continuous(
    
    # Features of the first axis
    name = "Close", limits = c(1900,3300),
    
    # Add a second axis and specify its features
    sec.axis = sec_axis(~./55, name="Negative Percent")
  )
#ggplot(anaPlusSPXJune, aes(Date,factor(Close),group=1))+geom_line()
```
```{r fig.width = 10}
ggplot(anaPlusSPXJune) +
  
  geom_line( aes(x=Date,y=Close, group = 1, color = "Closing Price SPX")) + 
  geom_line( aes(x=Date,y=NeuPercent*55, group = 1, color = "Neutral Percentage"))+ # Divide by 10 to get the same range than the temperature
  
  scale_y_continuous(
    
    # Features of the first axis
    name = "Close", limits = c(1800,3300),
    
    # Add a second axis and specify its features
    sec.axis = sec_axis(~./55, name="Neutral Percent")
  )
#ggplot(anaPlusSPXJune, aes(Date,factor(Close),group=1))+geom_line()
```
```{r fig.width = 10}
ggplot(anaPlusSPXJune) +
  
  geom_line( aes(x=Date,y=Close, group = 1, color = "Closing Price SPX")) + 
  geom_line( aes(x=Date,y=Polarity*8500, group = 1, color = "Polarity Daily Mean"))+ # Divide by 10 to get the same range than the temperature
  
  scale_y_continuous(
    
    # Features of the first axis
    name = "Close", limits = c(1000,3300),
    
    # Add a second axis and specify its features
    sec.axis = sec_axis(~./8500, name="Polarity Daily Mean")
  )
#ggplot(anaPlusSPXJune, aes(Date,factor(Close),group=1))+geom_line()
```

```{r}
library(ggpubr)
anaPlusSPXJune %>%
  ggplot(aes(x=Polarity,y=Close)) +
  geom_point(alpha=0.5) +
  labs(x= "Polarity", y="Close")+
  geom_smooth(method=lm)+
  stat_cor(method="pearson") 

```
```{r}
library(ggpubr)
anaPlusSPXJune %>%
  ggplot(aes(x=NeuPercent,y=PosPercent)) +
  geom_point(alpha=0.5) +
  labs(x= "NeuPercent", y="PosPercent")+
  geom_smooth(method=lm)+
  stat_cor(method="pearson") 

```
```{r}
library(ggpubr)
anaPlusSPXJune %>%
  ggplot(aes(x=NeuPercent,y=NegPercent)) +
  geom_point(alpha=0.5) +
  labs(x= "NeuPercent", y="NegPercent")+
  geom_smooth(method=lm)+
  stat_cor(method="pearson") 

```
```{r}
library(ggpubr)
anaPlusSPXJune %>%
  ggplot(aes(x=NegPercent,y=Close)) +
  geom_point(alpha=0.5) +
  labs(x= "Negative Percentage", y="Close")+
  geom_smooth(method=lm)+
  stat_cor(method="pearson") 

```
```{r}
library(ggpubr)
anaPlusSPXJune %>%
  ggplot(aes(x=PosPercent,y=Close)) +
  geom_point(alpha=0.5) +
  labs(x= "Positive Percentage", y="Close")+
  geom_smooth(method=lm)+
  stat_cor(method="pearson") 

```
```{r}
library(ggpubr)
anaPlusSPXJune %>%
  ggplot(aes(x=NeuPercent,y=Close)) +
  geom_point(alpha=0.5) +
  labs(x= "Neutral Percentage", y="Close")+
  geom_smooth(method=lm)+
  stat_cor(method="pearson") 

```

```{r}
mydata <- anaPlusSPXJune[, c(5,7,8,9,13)]
cormat <- round(cor(mydata),2)
View(cormat)
```
```{r}
library(reshape2)
melted_cormat <- melt(cormat)
head(melted_cormat)
```
```{r}
library(ggplot2)
ggheatmap <- ggplot(melted_cormat, aes(Var2, Var1, fill = value))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
    name="Pearson\nCorrelation") +
  theme_minimal()+ # minimal theme
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
 coord_fixed()
# Print the heatmap
print(ggheatmap)
```
```{r}
ggheatmap + 
geom_text(aes(Var2, Var1, label = value), color = "black", size = 4) 
```

```{r}
lm_modelA = lm(anaPlusSPXJune$Close~anaPlusSPXJune$NegPercent)
summary(lm_modelA)
```
```{r}
lm_modelB = lm(anaPlusSPXJune$PosPercent~anaPlusSPXJune$NegPercent)
summary(lm_modelB)
```
```{r}
lm_modelD = lm(anaPlusSPXJune$Close~anaPlusSPXJune$PosPercent)
summary(lm_modelD)
```
```{r}
lm_modelE = lm(anaPlusSPXJune$Close~anaPlusSPXJune$NeuPercent)
summary(lm_modelE)
```
```{r}
lm_modelC = lm(anaPlusSPXJune$Polarity~anaPlusSPXJune$NegPercent)
summary(lm_modelC)
```

```{r}
lm_model1 = lm(anaPlusSPXJune$Close~anaPlusSPXJune$Polarity)
summary(lm_model1)
```
```{r}
lm_model2 = lm(anaPlusSPXJune$Close~anaPlusSPXJune$PerSPX)
summary(lm_model2)
```
```{r}
require(lattice)
xyplot(anaPlusSPXJune$Close~anaPlusSPXJune$NegPercent, 
    grid = TRUE, type = c("p", "r"), col.line = "red", lwd = 3, ylab = "Daily Change of SPX Share Price in $", 
    xlab = "% of Negative Tweets", main = "% of Negative Tweets vs Daily
       SPX Share Price")
```
```{r}
# for the last hour
lastHRJune=read.csv('/Users/nickzelada/Desktop/Capstone/lastHRJune.csv')
```

```{r}
lastHRJune$Polarity[lastHRJune$Analysis == 'Positive'] <- 1
lastHRJune$Polarity[lastHRJune$Analysis == 'Neutral'] <- 0
lastHRJune$Polarity[lastHRJune$Analysis == 'Negative'] <- -1

```

```{r}
require(data.table)
result8 <- aggregate(Polarity~created_at, data= lastHRJune, FUN='mean')
```


```{r}
lastHRJune$created_at<-substr(lastHRJune$created_at,1,10)
```
```{r}
groupAnalysis8 = lastHRJune%>% group_by(created_at, Analysis)%>%count()
```
```{r}
anaNeu8 = subset(groupAnalysis8, Analysis == "Neutral")
anaNeg8 = subset(groupAnalysis8, Analysis == "Negative")
anaPos8 = subset(groupAnalysis8, Analysis == "Positive")


```
```{r}
colnames(anaNeu8)[3] <- "Neutral"
colnames(anaNeg8)[3] <- "Negative"
colnames(anaPos8)[3] <- "Positive"

```

```{r}
anaNeu8 = anaNeu8[-2]
anaNeg8 = anaNeg8[-2]
anaPos8 = anaPos8[-2]

```
```{r}
filtered8 <- aggregate(Polarity~created_at, data= lastHRJune, FUN='mean')
```
```{r}
ana8 = merge(anaNeg8, anaNeu8)
ana8 = merge(ana8,anaPos8)
ana8 = merge(ana8,filtered8)
```
```{r}
ana8$sum=ana8$Negative+ana8$Neutral+ana8$Positive
```
```{r}

ana8$NegPercent = round((ana8$Negative/ana8$sum)*100)
ana8$NeuPercent = round((ana8$Neutral/ana8$sum)*100)
ana8$PosPercent = round((ana8$Positive/ana8$sum)*100)
```
```{r}
colnames(ana8)[1] <- "Date"
#anaPlusSPX = inner_join(ana,spx, by= )
```
```{r}
groupAnalysisSpx8 = aggregate(lastHRJune$SPXCount, by=list(Category=lastHRJune$created_at), FUN=sum)
groupAnalysisSpx8
```
```{r}
groupAnalysisCovid8 = aggregate(lastHRJune$CovidCount, by=list(Category=lastHRJune$created_at), FUN=sum)
groupAnalysisCovid8
```
```{r}
colnames(groupAnalysisCovid8)[1] <- "Date"
colnames(groupAnalysisCovid8)[2] <- "CovidKeywords"
colnames(groupAnalysisSpx8)[1] <- "Date"
colnames(groupAnalysisSpx8)[2] <- "SPXKeywords"
```
```{r}
keyWordsMerge8 = inner_join(groupAnalysisSpx8,groupAnalysisCovid8, by= "Date" )
```


```{r}
anaPlusSPX8 = inner_join(ana8,spx, by= "Date" )
```
```{r}
anaPlusSPX8 = inner_join(anaPlusSPX8,keyWordsMerge8, by= "Date" )
```
```{r}
anaPlusSPX8$PerSPX = round((anaPlusSPX8$SPXKeywords/anaPlusSPX8$sum)*100)
anaPlusSPX8$PerCovid = round((anaPlusSPX8$CovidKeywords/anaPlusSPX8$sum)*100)
```
```{r fig.width = 10}
library(ggplot2)
library(ggthemes)
library(plotly)

graph10=ggplot(data=anaPlusSPX8 , aes(x = Date, y = Polarity))+
  geom_path(aes(group=1))+geom_point()
  
graph10

```


```{r}
allHRPolarity=summary(lm(anaPlusSPX8$Close~anaPlusSPX8$Polarity))
allHRPolarity
```
```{r}
library(ggpubr)
anaPlusSPX8 %>%
  ggplot(aes(x=Polarity,y=Close)) +
  geom_point(alpha=0.5) +
  labs(x= "Polarity", y="Close")+
  geom_smooth(method=lm)+
  stat_cor(method="pearson") 

```
```{r}
allHRNeg=summary(lm(anaPlusSPX8$Close~anaPlusSPX8$NegPercent))
allHRNeg
```
```{r}
library(ggpubr)
anaPlusSPX8 %>%
  ggplot(aes(x=NegPercent,y=Close)) +
  geom_point(alpha=0.5) +
  labs(x= "Negative Percentage", y="Close")+
  geom_smooth(method=lm)+
  stat_cor(method="pearson") 

```
```{r}
allHRPos=summary(lm(anaPlusSPX8$Close~anaPlusSPX8$PosPercent))
allHRPos
```
```{r}
library(ggpubr)
anaPlusSPX8 %>%
  ggplot(aes(x=PosPercent,y=Close)) +
  geom_point(alpha=0.5) +
  labs(x= "Positive Percentage", y="Close")+
  geom_smooth(method=lm)+
  stat_cor(method="pearson") 

```
```{r}
allHRNeu=summary(lm(anaPlusSPX8$Close~anaPlusSPX8$NeuPercent))
allHRNeu
```
```{r}
allHRNeu=summary(lm(anaPlusSPX8$Close~anaPlusSPX8$NeuPercent))
allHRNeu
```
```{r}
library(ggpubr)
anaPlusSPX8 %>%
  ggplot(aes(x=NeuPercent,y=Close)) +
  geom_point(alpha=0.5) +
  labs(x= "Neutral Percentage", y="Close")+
  geom_smooth(method=lm)+
  stat_cor(method="pearson") 

```
```{r}
allHRAll=lm(anaPlusSPX8$Close~anaPlusSPX8$NeuPercent+anaPlusSPX8$NegPercent+anaPlusSPX8$PosPercent)
summary(allHRAll)
```
```{r}
allHRAll1=lm(anaPlusSPX8$Close~anaPlusSPX8$NegPercent)
summary(allHRAll1)
```
```{r}
allHRAll3=lm(anaPlusSPX8$PosPercent~anaPlusSPX8$NeuPercent)
summary(allHRAll3)
```
```{r}
allHRAll4=lm(anaPlusSPX8$Close~anaPlusSPX8$PosPercent)
summary(allHRAll4)
```
```{r}
allHRAll5=lm(anaPlusSPX8$Close~anaPlusSPX8$NeuPercent)
summary(allHRAll5)
```
```{r}
allHRAll=lm(anaPlusSPX8$Close~anaPlusSPX8$PerSPX)
summary(allHRAll2)
```
```{r fig.width = 10}
ggplot(anaPlusSPX8) +
  
  geom_line( aes(x=Date,y=Close, group = 1, color = "Closing Price SPX")) + 
  geom_line( aes(x=Date,y=NeuPercent*55, group = 1, color = "Neutral Percentage"))+ 
  
  scale_y_continuous(
    
    # Features of the first axis
    name = "Close", limits = c(1800,3300),
    
    # Add a second axis and specify its features
    sec.axis = sec_axis(~./55, name="Neutral Percent")
  )
#ggplot(anaPlusSPXJune, aes(Date,factor(Close),group=1))+geom_line()
```




